spring:
  application:
    name: minhyeok-resource
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
elasticsearch:
  host: ${ELASTIC_HOST:localhost}
  port: ${ELASTIC_PORT:9200}
  expected-http-response-time-millis: ${ELASTIC_EXPECTED_HTTP_RESPONSE_TIME_MS:50}
  expected-throughput-in-request-per-seconds: ${ELASTIC_EXPECTED_REQUEST_PER_SEC:500}
  socket-timeout-seconds: ${ELASTIC_SOCKET_TIMEOUT_SEC:60}
  connection-timeout-seconds: ${ELASTIC_CONNECTION_TIMEOUT_SEC:30}
  connection-request-timeout-seconds: ${ELASTIC_CONNECTION_REQUEST_TIMEOUT_SEC:30}
  keep-alive-strategy-time-minutes: ${ELASTIC_KEEP_ALIVE_STRATEGY_TIME_MIN:5}
  scheme: http

app:
  version: @project.version@

server:
  servlet:
    context-path: /resource