elasticsearch:
  host: ${ELASTIC_HOST:localhost}
  port: ${ELASTIC_PORT:9200}
  expected-http-response-time-millis: ${ELASTIC_EXPECTED_HTTP_RESPONSE_TIME_MS:50}
  expected-throughput-in-request-per-seconds: ${ELASTIC_EXPECTED_REQUEST_PER_SEC:500}
  socket-timeout-seconds: ${ELASTIC_SOCKET_TIMEOUT_SEC:60}
  connection-timeout-seconds: ${ELASTIC_CONNECTION_TIMEOUT_SEC:30}
  connection-request-timeout-seconds: ${ELASTIC_CONNECTION_REQUEST_TIMEOUT_SEC:30}
  keep-alive-strategy-time-minutes: ${ELASTIC_KEEP_ALIVE_STRATEGY_TIME_MIN:5}
  scheme: http

client:
  id: oauth-client-id
  secret: oauth-client-secret
  redirectUrl: http://10.10.30.19:9000/oauth/login-call-back
  tenantId: 665092d1-905e-42db-a69b-e977952e8471
