### 생성
POST http://localhost:8080/resource/api/master/pGijL5EB2Nf0mCt0JTar/client/v1/create
Content-Type: application/json

{
  "clientId": "oauth-client-id-test",
  "clientName": "masterClient-test",
  "clientSecret": "oauth-client-secret-test",
  "redirectUris": [
    "http://127.0.0.1:8081"
  ],
  "scopes": [
    "read",
    "write"
  ]
}


### 수정
POST http://localhost:8080/resource/api/master/pGijL5EB2Nf0mCt0JTar/client/v1/oauth-client-id-test/update
Content-Type: application/json

{
  "clientName": "Example Client",
  "clientSecret": "example-client-secret-test",
  "registeredRedirectUri": [
    "https://example.com/redirect"
  ],
  "accessTokenValiditySeconds": 3600,
  "scopes": [
    "read",
    "write",
    "delete"
  ]
}

### 조회
GET http://localhost:8080/resource/api/master/pGijL5EB2Nf0mCt0JTar/client/v1/oauth-client-id
Content-Type: application/json

### 삭제
POST http://localhost:8080/resource/api/master/pGijL5EB2Nf0mCt0JTar/client/v1/oauth-client-id-test/delete