### 생성
POST http://localhost:8080/master/0c502f2c-9472-438a-be58-fb3b418b391d/user/v1/create
Content-Type: application/json

{
  "username": "master-user",
  "userId": "master@email.com",
  "email": "master@example.com",
  "password": "password123!",
  "scopes": ["read", "write"]
}

### 조회
GET http://localhost:8080/master/0c502f2c-9472-438a-be58-fb3b418b391d/user/v1/master@email.com
Content-Type: application/json


### 업데이트
POST http://localhost:8080/master/0c502f2c-9472-438a-be58-fb3b418b391d/user/v1/master@email.com/update
Content-Type: application/json

{
  "username": "update-master-user",
  "userId": "update@email.com",
  "email": "update@example.com",
  "password": "update123!",
  "scopes": ["read", "delete"]
}

### 삭제
POST http://localhost:8080/master/0c502f2c-9472-438a-be58-fb3b418b391d/user/v1/update@email.com/delete