### 생성
POST http://localhost:8080/api/v1/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiI0YTZjNDM4NC05MTA4LTQ5ZjctODhmNi1lMjZlNWY2ZTk0ZTMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyMzQ0NDQ3Mywic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyMzQ0NDc3MywiaWF0IjoxNzIzNDQ0NDczLCJqdGkiOiI1YTgzNDI1YS02YzlhLTRmNWEtOTAxZi0xN2NhNmUwMDhmMTYifQ.Tbfz1dLQAtNINu3RBxRj_w58aLBfyF-kGnsnOIgV5G2zAbvW64eHNlcTk5oSLOV_cGFK6Bgj7G5U4UJz9j2LOYHzGhKy4gZSTBNRRweqSRmCToPR-5ppsTtbS_dNfBl2aSSXmit1hyCOND5gAtZFoch_XlpLKxFpK6TU7cw-8IEPeq5dDoRIW0d6eE9yHYsaSXbZ19XF_gG-1qJ10UG2txYM9Eb0Stfn9f-rPUSFvIcYmxWdmCptWa4DdMabawGwahdnrk53nEZ5u3FT3y4Hl5Ptoy7c_KfblBuU_7jA7-IeujWYXQfHrs6z7lD-H0zuhFJd7MlgjmS9EBPTaGTrxw

{
  "tenantName": "lg"
}