### 생성
POST http://localhost:8080/api/v1/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIxNDkzMWI0NS0xN2Q0LTQwMTQtODQ2Ni1iZmI3NjRmZTNmMTAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyMzQyODY4Nywic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyMzQyODk4NywiaWF0IjoxNzIzNDI4Njg3LCJqdGkiOiI1MTZiN2E0OC05MDA4LTRhMjktOGU4NC1hZmY3OWJkZDYyYzMifQ.Gbl_qnvaaBPAGuK7LIxh-rFPB7YdLwpXJpRKIrmyFvYI5_F67NyaewemEaAlpGukjLl0TvOSLaVecsWPXhaHf7zN300WRzLRGM82wRA9i71FoCvXTtkM9nGThlChzTKMQpLWnAiWzbxlkLB7S0inZdTUYTdU3A8m49Pt3ePP4X5xzm1MACGoAKXVJZa6UTjTJXXDDxGHZ0xaA0M-L_bvdWb_Aio9oDcecVe0gpnN_SFsljms_ojN3Zd5L-5HoKSpBrSLjfCTmLMplQKo6SyChp9KcwVW0slcqchi1STtwo2ICUytdqsKc6vvLHfaac_5Mz6rmJJCZqjsjc4mD7-brg

{
  "tenantName": "sk"
}