### 토큰삭제
DELETE http://localhost:8080/resource/api/v1/access-token
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJiNDAwNjQxMS1lMzcyLTRmOWItOTQ4Ni01ODZkMmVjNTgyOWMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyMzc4MjMzOSwic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyMzc4MjYzOSwiaWF0IjoxNzIzNzgyMzM5LCJqdGkiOiI5YmI1N2MzNy1iM2EyLTRlNzMtOTIyMS1mYzNiZmUzMTI2ZGMifQ.IUyuErSZRZQcSfs4FHdGs4Z1IA66v0HHlYm6l2tVIQo6LuW9FgqZP84C9jmCSifEcn0f1k8WwXNsVC7vPBw_dHsxlnzkGOGfqgYhnFN9_eMSUzijlsg2IYm4dUuRdIpfH5o7TlX_AYwbPdISXbjY19l8GvJECSZCjHp94DJGGMf5KIvZST6i3km2Bfymqk5y5Ws8ipSVO3YAcdkYSOfDSLtj4OzTxydChlLuK0ihxbdBBPdgn-fPtx-I1f1EjDj4vAGvj4vo4eHxIMbVJOH41pA3o91MZzMUYpvBRL7v0zyik0SUl8I0P81Yg6uQZBpHpD26SBLTzVUrB2JUW8_dWg

{
  "accessToken" : "eyJraWQiOiIzODE2NGM2ZC01NGQxLTQyODctOWIzMS03OGU1NWVjNGI2ZTkiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyMzc4MTA1OSwic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyMzc4MTM1OSwiaWF0IjoxNzIzNzgxMDU5LCJqdGkiOiJmZGIyZGM3Zi1iZWE1LTQ1NjctOTFmYy1iNjE0ZjkxZWRlNWYifQ.MFc5Lz6-Ms2PcgOJ_OE1pD8_psDM-zOJMGarm3hEP2Fy3GteS8sBGUDgBh_xjZtxBiAvNjHsOn7b10bwXLj99r14FNek2sUdu5HRZ5kemdqiyRAcLqKIJI6KO_2mNMCdx6DqdCwlOqyxBrpAQdw81iD1LfR3Ebs5CC5nksjNNcJJICo8H8VL2KoAHH-x9TmcTh8eTsvtCixKTN1tVdUX3ldFo30L4jfRaqoWEezFJ5Wxhgj2-pTNSV7fW7ilSYk6hTQQbUbaDOVR0MZJEWdIjyLa6I4_YGemicluct_PCHCxaeCDmJ4U1ytQ144hNrMrtbT84pdAG4BUFP1_yHtBOg"
}