### ADMIN 유저 생성
POST http://localhost:8080/api/0c502f2c-9472-438a-be58-fb3b418b391d/amdin/user/v1/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIxNDkzMWI0NS0xN2Q0LTQwMTQtODQ2Ni1iZmI3NjRmZTNmMTAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyQGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyMzQyNDg0MCwic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyMzQyNTE0MCwiaWF0IjoxNzIzNDI0ODQwLCJqdGkiOiI2NTlkOTBmMC1hNTdjLTRmODEtYjA3MC0xMDZiOTQ2NDE4M2QifQ.FXVK6M0JDy7tmpPBEUo9b0LAzC24Ew8fvC2iny09rPnJoAuEwgV6Zv1XXevz0FCyucydU79nlSr212rKqhythtAxHOV5YlMd5w7-QtWbqRizwnKAO5gZitvAjrFgTz_hHt9vUbXkpLTuy_JbYg-0Y093RrlgOuI69a-fCKQ6yJcRtGjESixLfXuUZh7HE8M6oCynZ4HxiGqBdhWphN5k0aRFHb_f-kNSSz5ihiCkeaegsvU0Z7DPT2bZgQWBlxxkbDRae0hAiLi-iW6NWbaUspwcXv33AI_MlQICgIp_x7NmO7XUUq9rZked2-IqzyxPHlfpLNc0XP5aY_s6WM8OdQ

{
  "username": "sk-admin-user",
  "userId": "admin@email.com",
  "email": "admin@example.com",
  "password": "1234",
  "scopes": ["read", "write"]
}

### 일반 유저 생성
POST http://localhost:8080/api/0c502f2c-9472-438a-be58-fb3b418b391d/user/v1/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIxNDkzMWI0NS0xN2Q0LTQwMTQtODQ2Ni1iZmI3NjRmZTNmMTAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJza3VzZXJAZW1haWwuY29tIiwiYXVkIjoib2F1dGgtY2xpZW50LWlkIiwibmJmIjoxNzIzNDI4MTE5LCJzY29wZSI6WyJ3cml0ZSIsInJlYWQiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzIzNDI4NDE5LCJpYXQiOjE3MjM0MjgxMTksImp0aSI6ImNjYmIwZWNmLTBlNTctNDFhNi05ZjRjLWRkMzNkNTYzNGQ5MiJ9.SJctscOgLw3-_9kz-96wZB4oqdp_RCaGaXtIv9h0pIlA7a1ssXSk3A4hSSaz_KoGUb3yzajXbGhVrtRzbvtgk9ksWojdAK5Bp0fsJFS_EJES-YzierZmmC13V4YXOrZ7sbxknG9HGUZtMtp1bkk7arre89qQX3PMBj4GFlQjXIIoYTPDSYYDrP22_BTO-jdLcr_i2sNsjjfS6ME7OwjZaGSJpEUUDX8OH36d39f52sr3qjr3yGZ2NKGgyUroFx-6OVDmZAP0MUNAw5VrR8EXG85MVq1K5A7wf4yPfLX5iIEYCXppRn8LSmcsV7ox0hzoXElLDG8HToT8_kyTxVMLgQ

{
  "username": "sk-user",
  "userId": "skuser@email.com",
  "email": "skuser@example.com",
  "password": "1234",
  "scopes": ["read", "write"]
}