### ADMIN 유저 생성
POST http://localhost:8080/api/admin/XBaUSZEBkKEDlp8emDGh/user/v1/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIyZDY3MjA2ZS1hZDZlLTQyMzEtOGI3My0yYmE4YzY4ZTMzYWYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyMzUyNjc5MSwic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyMzUyNzA5MSwiaWF0IjoxNzIzNTI2NzkxLCJqdGkiOiIzMmIxNjAwYy1hMDJhLTQ1MTQtODkzYy0zZGU1ZjhlMmE1ZGEifQ.cjE-b3kuCMPxOIJccSjjIlCYWQ2wgSMGEknkfttZ55dvodhtX8GYqT44tUuEkvG6fq4MhTh_w-UAz0C0eDohpPnIv83iD5sskxO_i-DM3OEElUTDdaB5CJ1D_hRUvrKGA88gk4-JAJaVALKg0yMYYvI7HV89r34_gxsdPF7V12EcPiUzTSt-wqNL1LPu2KSyXTS7iVB3XHN6P81Ow2JyuAlcgbAhTYaMw80bEplRDTc47YBZSs2qTp_CKP8ta705IK_phi6UExffZyru1UofiONQ5U7WGrRz58UXPVXv4M96pCMG6USPIuTjeQPn6e0VEu6O1BlcPgGw3ecbe4UmLg

{
  "username": "lg-admin-user",
  "userId": "lg@email.com",
  "email": "lg@example.com",
  "password": "1234",
  "scopes": ["read", "write"]
}

### 일반 유저 생성
POST http://localhost:8080/api/XBaUSZEBkKEDlp8emDGh/user/v1/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiI2NDZlZmRiMy04NDc5LTRmYTgtYTkxYS1jNjI1NzdiYTU3OTAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsZ3VzZXIzQGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyMzUyODI2MSwic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyMzUyODU2MSwiaWF0IjoxNzIzNTI4MjYxLCJqdGkiOiJjYjhhNDJlNS0zMjdhLTQxMDgtODY2Ny01MDQ3ODRmMWUyMTcifQ.SGA_i28l4mifi5tBOYlGUeGaBIx3au94yG_srfkmpfCLKNlC5RFbHvdcWTU3qMhC7BCbJ2x_11EVNAHejXNU2YWoF1FZP-ES7EXTjC8cztq8oWE84YfyYvlRqiZdmwtaMPN9FmF244aFEnXJNgzApkJJ2YyuaV0BLwmRM5OycCV7_763Nvq_neRAtxyOG7qZaVmIg2VYa0aq2y5R6Gdp7xG1rugp1dkbh8SE02K8HHIjdPqUZMQMHqGvLRm-D2eF0ijEwgSS2uUWg4RpBijel60U0nNz9EnlqxuicDvMH6p2ou4T63FZa4PZ8ygra0xO0j12PQd6xwWPnaF5xuxUcA

{
  "username": "lg3-user",
  "userId": "lguser3@email.com",
  "email": "lguser3@example.com",
  "password": "1234",
  "scopes": ["read", "write"]
}