### ADMIN 유저 생성
POST http://localhost:8080/resource/api/admin/XBaUSZEBkKEDlp8emDGh/user/v1/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJkNWQ2MmFjOC02YTAyLTQxNmEtOGU2NC1hNmI0NmExZDEyYjQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyNDIyMjg4OSwic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyNDIyMzE4OSwiaWF0IjoxNzI0MjIyODg5LCJqdGkiOiJjNjE3NTM1Yi00MDVjLTQwODUtOTBmNC03ZWRhZTY5ZDhkNjMifQ.EyJttIb7Xq2_8jl-qIVVUpJZpyjuP33n_GB0QV2i8mCbJe8O7Z2zM6zuq28rNqMqRnIHCvdGHf3GAedw7hYAROAoJPTheimfXqU_c3c_ifrzl9eGl6UVyXvrI2XL3cFks2GH0Sxs2uQV2oo0yN1jX800kKAkSEj-oPHlqbimKQUsnY8NZBl2JvSZVtwsfdh5nzsf-dS-eqYA_XPsZ-l1HPkSkJ3SKXX8psbrTibwlBCjiyS5NyS7z7-Kt8LZ8-V43WMFGYzq-yWygTIY5zWU-Gs9hztwhXUb5eX2h92-1AD_NvGBz6No-LgWHSC0JW5o11c1ZBWu07bRzhJVzwxcWw

{
  "username": "lg-admin-user",
  "userId": "lg@email.com",
  "email": "lg@example.com",
  "password": "1234",
  "scopes": ["read", "write"]
}

### 일반 유저 생성
POST http://localhost:8080/resource/api/XBaUSZEBkKEDlp8emDGh/user/v1/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJkNWQ2MmFjOC02YTAyLTQxNmEtOGU2NC1hNmI0NmExZDEyYjQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImF1ZCI6Im9hdXRoLWNsaWVudC1pZCIsIm5iZiI6MTcyNDIyMjg4OSwic2NvcGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcyNDIyMzE4OSwiaWF0IjoxNzI0MjIyODg5LCJqdGkiOiJjNjE3NTM1Yi00MDVjLTQwODUtOTBmNC03ZWRhZTY5ZDhkNjMifQ.EyJttIb7Xq2_8jl-qIVVUpJZpyjuP33n_GB0QV2i8mCbJe8O7Z2zM6zuq28rNqMqRnIHCvdGHf3GAedw7hYAROAoJPTheimfXqU_c3c_ifrzl9eGl6UVyXvrI2XL3cFks2GH0Sxs2uQV2oo0yN1jX800kKAkSEj-oPHlqbimKQUsnY8NZBl2JvSZVtwsfdh5nzsf-dS-eqYA_XPsZ-l1HPkSkJ3SKXX8psbrTibwlBCjiyS5NyS7z7-Kt8LZ8-V43WMFGYzq-yWygTIY5zWU-Gs9hztwhXUb5eX2h92-1AD_NvGBz6No-LgWHSC0JW5o11c1ZBWu07bRzhJVzwxcWw

{
  "username": "lg3-user",
  "userId": "lguser3@email.com",
  "email": "lguser3@example.com",
  "password": "1234",
  "scopes": ["read", "write"]
}